//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWEditor6.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWEditor6.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct VertexInput
        ///{
        ///	float2 position : POSITION0;
        ///	float2 texCoord : TEXCOORD0;
        ///};
        ///
        ///struct VertexOutput
        ///{
        ///	float4 position : SV_Position;
        ///	float2 texCoord : TEXCOORD0;
        ///};
        ///
        ///VertexOutput main(VertexInput input) {
        ///	VertexOutput output = (VertexOutput) 0;
        ///	output.position = float4(input.position, 0, 1);
        ///	output.texCoord = input.texCoord;
        ///
        ///	return output;
        ///}.
        /// </summary>
        internal static string TexturedQuadVertex {
            get {
                return ResourceManager.GetString("TexturedQuadVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct PixelInput
        ///{
        ///	float4 position : SV_Position;
        ///	float2 texCoord : TEXCOORD0;
        ///};
        ///
        ///Texture2D quadTexture : register(t0);
        ///SamplerState quadSampler : register(s0);
        ///
        ///float4 main(PixelInput input) : SV_Target {
        ///	return quadTexture.Sample(quadSampler, input.texCoord);
        ///}.
        /// </summary>
        internal static string TextureQuadPixel {
            get {
                return ResourceManager.GetString("TextureQuadPixel", resourceCulture);
            }
        }
    }
}
