//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoundingBoxPixel {
            get {
                object obj = ResourceManager.GetObject("BoundingBoxPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BoundingBoxVertex {
            get {
                object obj = ResourceManager.GetObject("BoundingBoxVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Add {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Add_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Add_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_AddAlpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_AddAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_AddAlpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_AddAlpha_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_AddNA {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_AddNA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Dual_Crossfade {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Dual_Crossfade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Masked_Dual_Crossfade {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Masked_Dual_Crossfade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Mod2x {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Mod2x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Mod2xNA {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Mod2xNA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod_Opaque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Mod1 {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Mod1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_AddAlpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_AddAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_AddAlpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_AddAlpha_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_AddAlpha_Wgt {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_AddAlpha_Wgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Alpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Alpha_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Mod", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Mod2x {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Mod2x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Mod2xNA {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Mod2xNA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Mod2xNA_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Mod2xNA_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_ModNA_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_ModNA_Alpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque_Opaque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel_PS_Combiners_Opaque1 {
            get {
                object obj = ResourceManager.GetObject("M2Pixel_PS_Combiners_Opaque1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel2PassOld {
            get {
                object obj = ResourceManager.GetObject("M2Pixel2PassOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2Pixel3PassOld {
            get {
                object obj = ResourceManager.GetObject("M2Pixel3PassOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelBlendAlphaOld {
            get {
                object obj = ResourceManager.GetObject("M2PixelBlendAlphaOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelBlendOld {
            get {
                object obj = ResourceManager.GetObject("M2PixelBlendOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelOld {
            get {
                object obj = ResourceManager.GetObject("M2PixelOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelPortrait {
            get {
                object obj = ResourceManager.GetObject("M2PixelPortrait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelPortrait2Pass {
            get {
                object obj = ResourceManager.GetObject("M2PixelPortrait2Pass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelPortrait3Pass {
            get {
                object obj = ResourceManager.GetObject("M2PixelPortrait3Pass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelPortraitBlend {
            get {
                object obj = ResourceManager.GetObject("M2PixelPortraitBlend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2PixelPortraitBlendAlpha {
            get {
                object obj = ResourceManager.GetObject("M2PixelPortraitBlendAlpha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_EdgeFade_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_EdgeFade_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_EdgeFade_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_Env_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_Env_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_T1_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T1_T2_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T2_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T11 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstanced_VS_Diffuse_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexInstancedOld {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstancedOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexPortrait {
            get {
                object obj = ResourceManager.GetObject("M2VertexPortrait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_EdgeFade_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_EdgeFade_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_EdgeFade_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_Env_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_Env_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_T1_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T1_T2_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T2_T1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T11 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingle_VS_Diffuse_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] M2VertexSingleOld {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingleOld", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MapLowPixel {
            get {
                object obj = ResourceManager.GetObject("MapLowPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MapLowVertex {
            get {
                object obj = ResourceManager.GetObject("MapLowVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkyPixel {
            get {
                object obj = ResourceManager.GetObject("SkyPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkyVertex {
            get {
                object obj = ResourceManager.GetObject("SkyVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainPixel {
            get {
                object obj = ResourceManager.GetObject("TerrainPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainPixelNew {
            get {
                object obj = ResourceManager.GetObject("TerrainPixelNew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TerrainVertex {
            get {
                object obj = ResourceManager.GetObject("TerrainVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TexturedQuadPixel {
            get {
                object obj = ResourceManager.GetObject("TexturedQuadPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TexturedQuadVertex {
            get {
                object obj = ResourceManager.GetObject("TexturedQuadVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WmoPixel {
            get {
                object obj = ResourceManager.GetObject("WmoPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WmoPixelBlend {
            get {
                object obj = ResourceManager.GetObject("WmoPixelBlend", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WmoPixelBlendIndoor {
            get {
                object obj = ResourceManager.GetObject("WmoPixelBlendIndoor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WmoPixelIndoor {
            get {
                object obj = ResourceManager.GetObject("WmoPixelIndoor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WmoVertex {
            get {
                object obj = ResourceManager.GetObject("WmoVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorldTextPixel {
            get {
                object obj = ResourceManager.GetObject("WorldTextPixel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorldTextVertex {
            get {
                object obj = ResourceManager.GetObject("WorldTextVertex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorldTextVertexOrtho {
            get {
                object obj = ResourceManager.GetObject("WorldTextVertexOrtho", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
