//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string BoundingBoxFragment {
            get {
                object obj = ResourceManager.GetObject("BoundingBoxFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string BoundingBoxVertex {
            get {
                object obj = ResourceManager.GetObject("BoundingBoxVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Add {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Add", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Add_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Add_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_AddAlpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_AddAlpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_AddAlpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_AddAlpha_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_AddNA {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_AddNA", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Dual_Crossfade {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Dual_Crossfade", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Masked_Dual_Crossfade {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Masked_Dual_Crossfade", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Mod", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Mod2x {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Mod2x", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Mod2xNA {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Mod2xNA", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod_Opaque", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Mod1 {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Mod1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_AddAlpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_AddAlpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_AddAlpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_AddAlpha_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_AddAlpha_Wgt {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_AddAlpha_Wgt", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Alpha_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Alpha_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Mod {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Mod", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Mod2x {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Mod2x", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Mod2xNA {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Mod2xNA", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Mod2xNA_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Mod2xNA_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_ModNA_Alpha {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_ModNA_Alpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque_Opaque {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque_Opaque", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment_PS_Combiners_Opaque1 {
            get {
                object obj = ResourceManager.GetObject("M2Fragment_PS_Combiners_Opaque1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment2PassOld {
            get {
                object obj = ResourceManager.GetObject("M2Fragment2PassOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2Fragment3PassOld {
            get {
                object obj = ResourceManager.GetObject("M2Fragment3PassOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentBlendAlphaOld {
            get {
                object obj = ResourceManager.GetObject("M2FragmentBlendAlphaOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentBlendOld {
            get {
                object obj = ResourceManager.GetObject("M2FragmentBlendOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentOld {
            get {
                object obj = ResourceManager.GetObject("M2FragmentOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentPortrait {
            get {
                object obj = ResourceManager.GetObject("M2FragmentPortrait", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentPortrait2Pass {
            get {
                object obj = ResourceManager.GetObject("M2FragmentPortrait2Pass", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentPortrait3Pass {
            get {
                object obj = ResourceManager.GetObject("M2FragmentPortrait3Pass", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentPortraitBlend {
            get {
                object obj = ResourceManager.GetObject("M2FragmentPortraitBlend", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2FragmentPortraitBlendAlpha {
            get {
                object obj = ResourceManager.GetObject("M2FragmentPortraitBlendAlpha", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_EdgeFade_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_EdgeFade_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_EdgeFade_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_EdgeFade_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_Env_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_Env_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_Env_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_Env_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_T1_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T1_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T1_T2_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T1_T2_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T11 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T11", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstanced_VS_Diffuse_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstanced_VS_Diffuse_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexInstancedOld {
            get {
                object obj = ResourceManager.GetObject("M2VertexInstancedOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexPortrait {
            get {
                object obj = ResourceManager.GetObject("M2VertexPortrait", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_EdgeFade_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_EdgeFade_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_EdgeFade_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_EdgeFade_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_Env_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_Env_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_Env {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_Env_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_Env_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_Env_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_T1_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_T1_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T1_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T1_T2_T1 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T1_T2_T1", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T11 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T11", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingle_VS_Diffuse_T2 {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingle_VS_Diffuse_T2", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string M2VertexSingleOld {
            get {
                object obj = ResourceManager.GetObject("M2VertexSingleOld", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MapLowFragment {
            get {
                object obj = ResourceManager.GetObject("MapLowFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string MapLowVertex {
            get {
                object obj = ResourceManager.GetObject("MapLowVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string SkyFragment {
            get {
                object obj = ResourceManager.GetObject("SkyFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string SkyVertex {
            get {
                object obj = ResourceManager.GetObject("SkyVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string TerrainFragment {
            get {
                object obj = ResourceManager.GetObject("TerrainFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string TerrainFragmentNew {
            get {
                object obj = ResourceManager.GetObject("TerrainFragmentNew", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string TerrainVertex {
            get {
                object obj = ResourceManager.GetObject("TerrainVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string TexturedQuadFragment {
            get {
                object obj = ResourceManager.GetObject("TexturedQuadFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string TexturedQuadVertex {
            get {
                object obj = ResourceManager.GetObject("TexturedQuadVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WmoFragment {
            get {
                object obj = ResourceManager.GetObject("WmoFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WmoFragmentBlend {
            get {
                object obj = ResourceManager.GetObject("WmoFragmentBlend", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WmoFragmentBlendIndoor {
            get {
                object obj = ResourceManager.GetObject("WmoFragmentBlendIndoor", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WmoFragmentIndoor {
            get {
                object obj = ResourceManager.GetObject("WmoFragmentIndoor", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WmoVertex {
            get {
                object obj = ResourceManager.GetObject("WmoVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WorldTextFragment {
            get {
                object obj = ResourceManager.GetObject("WorldTextFragment", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WorldTextVertex {
            get {
                object obj = ResourceManager.GetObject("WorldTextVertex", resourceCulture);
                return ((string)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.String.
        /// </summary>
        internal static string WorldTextVertexOrtho {
            get {
                object obj = ResourceManager.GetObject("WorldTextVertexOrtho", resourceCulture);
                return ((string)(obj));
            }
        }
    }
}
