//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWEditor6.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWEditor6.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render Window.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to generate a WDL for this continent. When generating the WDL file the height data is taken from the data in your archives (CASC or MPQ) and the existing files in the Output folder. This means that changes to your terrain files that were not saved yet will not be considered in the process of creating the WDL file.
        ///
        ///Would you like to automatically save all your changes to the terrain files now? If you check the checkbox your choice will be remember and the next time you click the &apos;Generate WD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Message_AutosaveOnWdl {
            get {
                return ResourceManager.GetString("Message_AutosaveOnWdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the newest version of the world of warcraft map editor.
        ///
        ///Before you can start please make sure you select the path to your world of warcraft directory. Right now all that is supported is CASC based installations of the game. Basically this means its Warlords of Draenor only. There is already a basic layout set up for MPQ. 
        ///
        ///Please do not select the data folder or the wow.exe itself, just select the directory your wow is installed in. If you wanna let it be loaded from the registry (this usual [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SplashView_AppDescription {
            get {
                return ResourceManager.GetString("SplashView_AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft Editor.
        /// </summary>
        internal static string SplashView_AppTitle {
            get {
                return ResourceManager.GetString("SplashView_AppTitle", resourceCulture);
            }
        }
    }
}
